import { test, expect } from './support/fixtures.js'
import { TOKENS, MOCK } from './support/config.js'
import { jsonRoute, wpErrorRoute } from './support/mock.js'

/**
 * Pixel baselines of the React screen, under screenshots.spec.js-snapshots/. CI only:
 * they are Linux renders (fonts differ per platform), regenerated by running the CI
 * workflow by hand with "update screenshots" on and committing its artifact. Every
 * Ploi-backed response is mocked or pinned, so no image depends on the account
 * behind the token. The footer stays out of frame: its version line changes every release.
 */
async function shoot(settings, name) {
  // WHY: the wp-admin chrome above the screen ends on a sub-pixel boundary on 6.6 and a whole
  // pixel on 7.1, so the same screen rasterises differently; snapping it to the pixel grid
  // lets one baseline serve both WordPress versions. Padding on the mount, not a margin: the
  // screen's own top margin collapses through the mount.
  await settings.root.evaluate((root) => {
    const fraction = root.getBoundingClientRect().top % 1
    if (fraction) root.parentElement.style.paddingTop = `${1 - fraction}px`
    if (root.getBoundingClientRect().top % 1) throw new Error('[e2e] The screen is still off the pixel grid.')
  })
  await expect(settings.root).toHaveScreenshot(name)
}

const ENTRIES = [
  { id: 4, created_at: 'July 12, 2026 4:00 pm', reason_label: 'Manual flush', server_id: '12345', site_id: '67890', success: true, http_code: 200, hint: '', message: '', duration_ms: 412 },
  { id: 3, created_at: 'July 12, 2026 3:00 pm', reason_label: 'Post published or updated', server_id: '12345', site_id: '67890', success: true, http_code: 200, hint: '', message: '', duration_ms: 388 },
  { id: 2, created_at: 'July 12, 2026 2:00 pm', reason_label: 'Manual flush', server_id: '12345', site_id: '67890', success: false, http_code: 404, hint: 'Ploi could not find the server or site — it may have been deleted.', message: 'Unable to find this record.', duration_ms: 95 },
  { id: 1, created_at: 'July 12, 2026 1:00 pm', reason_label: 'Comment posted or moderated', server_id: '12345', site_id: '67890', success: false, http_code: 0, hint: '', message: 'Could not resolve host: ploi.io', duration_ms: 3002 },
]

test.describe('Screenshots', () => {
  test.skip(!process.env.CI, 'CI only: the baselines are Linux renders')
  test.skip(!TOKENS.good, 'needs the good Ploi token in .claude/.env')

  test('settings tab, connected', async ({ connected, admin, api, settings }) => {
    const canonical = await api.ensureBaseline()
    await api.setTarget({ ...canonical, server_name: 'production', site_domain: 'example.com' })
    try {
      await admin.reload()
      await shoot(settings, 'settings-connected.png')
    } finally {
      await api.setTarget(canonical)
    }
  })

  test('settings tab, disconnected', async ({ connected, admin, api, settings }) => {
    await api.disconnect()
    await admin.reload()
    await expect(settings.connectButton).toBeVisible()
    await shoot(settings, 'settings-disconnected.png')
  })

  test('settings tab, reconnect banner', async ({ connected, admin, settings }) => {
    await wpErrorRoute(admin, MOCK.flush, 'ploi_error', 'Ploi rejected the request.', 401)
    await settings.flushNowButton.click()
    await expect(settings.reconnectBanner).toBeVisible()
    await settings.waitForFlushSettled()
    await shoot(settings, 'settings-reconnect.png')
  })

  test('logs tab', async ({ connected, admin, settings }) => {
    await jsonRoute(admin, MOCK.log, { entries: ENTRIES })
    await settings.logsTab.click()
    await settings.logRefreshButton.click()
    await expect(settings.logRows).toHaveCount(ENTRIES.length)
    await shoot(settings, 'logs.png')
  })

  test('target dialog', async ({ connected, admin, api, settings }) => {
    const saved = await api.settings()
    await jsonRoute(admin, MOCK.connection, {
      state: 'ok',
      servers: [{ id: saved.serverId, name: 'production' }, { id: 'mock-staging', name: 'staging' }],
      sites: [],
    })
    await jsonRoute(admin, MOCK.sites, { sites: [{ id: saved.siteId, domain: 'example.com' }, { id: 'mock-blog', domain: 'blog.example.com' }] })

    await settings.openTargetModal()
    await expect(settings.siteSelect).toHaveValue(String(saved.siteId))
    await expect(settings.modal).toHaveScreenshot('target-dialog.png')
  })
})
